server:
  port: 8088

spring:

  datasource:
    url: jdbc:h2:mem:auction_db
#    url: jdbc:h2:file:~/2020jin/data/auction_db
#    file로 설정하면 해당 위치에 파일로 떨어짐
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
